### PR TITLE
12191 [ios] moved .podspec

### PR DESCRIPTION
**Pull request by adam-govan**
moved the .podspecs for Conversation/ Common and SwrveSDK to the root directory of the repo so then they can be seen by our local tester applications

@Sergio-Mira / @dominicmarmionswrve

### CODE REVIEW

**Comment by Sergio-Mira** [comment]
Do we have two copies of the pod specs now?

**Comment by adam-govan** [comment]
@Sergio-Mira no, we moved the podspecs into root of the repo and updated all of them to point to their respective directories

**Comment by Sergio-Mira** [comment]
I can see both SwrveConversationSDK/SwrveConversationSDK.podspec and SwrveConversationSDK.podspec

**Comment by seaders** [comment]
That's my bad, correcting now.

**Comment by seaders** [comment]
All good now @Sergio-Mira.

**Comment by Sergio-Mira** [comment]
:rocket:

**Pull request merged**
