### PR TITLE
be able to compile using Xcode 9 setting the minimum version to iOS 7.0

### PR DESCRIPTION
**Pull request by heyzooi**
be able to compile using Xcode 9 setting the minimum version to iOS 7.0

### CODE REVIEW

**Comment by Sergio-Mira** [comment]
Thanks @heyzooi we'll look into solving compilation issues with minimum version set to iOS 7.0.

**Comment by Sergio-Mira** [comment]
Hi @heyzooi how could I reproduce the error you are seeing? Xcode 9 doesn't let you set the target to iOS7 anymore, I added it by manually editing the sample ObjC MessageCenter and I got no compiler error. What kind of error are you getting, could you share it with us?

**Comment by heyzooi** [comment]
It's not the minimum version for the project, but the minimum version for the storyboard `SwrveConversation.storyboard`. You can see this in the `File Inspector` tab.

screenshot

**Comment by Sergio-Mira** [comment]
Are you changing manually the deployment target of that storyboard? If the project setting is changed and the SDK is untouched we are not getting any errors.

**Pull request closed without merging**
