### PR TITLE
Fixes #242 - Fails to compile on Xcode 9.3 & Swift 4.1

### LINKED ISSUE #242: 5.2.1 Fails to compile on Xcode 9.3 & Swift 4.1
The SDK fails to compile with the error: `Duplicate interface definition for class 'SwrvePush'`

Also there's the warning: `Duplicate protocol definition of 'SwrvePushResponseDelegate' is ignored`

### PR DESCRIPTION
**Pull request by ababeel**

### CODE REVIEW

**Comment by ejmartin504** [comment]
Tried pointing to this branch locally, compilation still fails in my project on Xcode 9.3

**Comment by ababeel** [comment]
hi @ejmartin504 , no issues here with 9.3 with this change, both if compiled separately or changed directly in other project( just remove line #24 from SwrveSDKCommon-umbrella.h), what error are you getting ?

**Comment by ejmartin504** [comment]
I am using Cocoapods 1.4 to install Swrve in my project. If I install directly from this commit, I get the same "duplicate definition for SwrvePush" error referenced in #242 

If I remove line 24 from the umbrella header manually after pod installing, everything works as expected! Does that change also need to land on this branch, or?

**Comment by KevBrodigan** [comment]
Hey Guys, these issues have been addressed in the latest release 5.2.2

**Comment by ejmartin504** [comment]
Wonderful, thanks @KevBrodigan!

**Comment by DNAngeluS** [comment]
Hi @KevBrodigan , thanks for that quick work!.
Just wanted to let your know that your fix worked for some of the errors that I was having. I had to add a #ifndef rule also in SwrveSDK.h at the Public Headers files cause it was giving me the same duplicate error.

Cheers!

**Pull request closed without merging**
