### PR TITLE
Add A/B testing update call back

### PR DESCRIPTION
**Pull request by Cyklet**
Hello, this PR will add the possibility to handle when A/B testing resources will be changed.

### CODE REVIEW

**Comment by Sergio-Mira** [comment]
What is the difference with resourcesUpdatedCallback?

**Comment by S2dentik** [comment]
@Sergio-Mira when the `ab_test_details` are coming, the `user_resources` field is `nil`, so that callback is not invoked. So we could either make the `resourcesUpdatedCallback` a more universal one, being called everytime some API answer is received, or separate them (which sounds more targeted)

**Comment by Cyklet** [comment]
Hi Sergio-Mira

We have encountered some problems getting the call back when the A/B testing was loaded, I will try to describe what is happening (`ab_test_details` for the request is set to 1)

When the new instance of SwrveSDK was set with configuration `startCampaignsAndResourcesTimer` is calling and after all `user_resources_and_campaigns` request is made. The first-time response comes with the next values:
___
First Case
```
campaigns are an empty array
ab_test_details is empty dictionary
user_resources is filled with data
```
everything works as expected 
`resourcesUpdatedCallback` is called 2 times -> first time because you are calling `[self updateResources:resourceJson writeToCache:YES];` and second time after `if (![self campaignsAndResourcesInitialized]) {`( After this `setCampaignsAndResourcesInitialized` will be true , that's mean that on the next request `resourcesUpdatedCallback` will be called only once in `[self updateResources:resourceJson writeToCache:YES];`)
___
As I said `ab_test_details` is empty and when we will try to get `abTestDetails` from `SwrveResourceManager` it will be an empty array

After this, the `refreshCampaignsAndResources:(NSTimer*)timer` function is called with the same request `user_resources_and_campaigns` and same properties, but this time we will get next response:
___
Second Case
```
campaigns are filled with data
ab_test_details is filled with data
user_resources is nil
```
So as you see we get `user_resources` nil, and `[self updateResources:resourceJson writeToCache:YES];` will not be called
___
I have tried to call `refreshCampaignsAndResources` manually after some time and I got the same behaviour as in the Second Case

If it is the expected behaviour then I have a proposal to apply the single responsibility principle for the callbacks, one that will handle resources updates and the second one that will handle A/B testing updates.

Best Regards,
Petre

**Comment by Sergio-Mira** [comment]
It is the expected behaviour. We compare what the client has against the response from the server using etags and if they have not changed we send nil, which in turn makes the client keep what it had and not call the callback as there haven't been any updates to resources.

**Comment by S2dentik** [comment]
@Sergio-Mira what about A/B tests? Is it expected that on first launch we have no callback about their values? Also no update when something changes. Shouldn't we have something similar for them, as we have for resources?

**Comment by Sergio-Mira** [comment]
We could add a listener for ab_test_details 👍 We'll look into adding this in an upcoming release.

**Comment by KevBrodigan** [comment]
Closing due to lack of customer requests for this feature. Can re examine in future if required

**Pull request closed without merging**
