### PR TITLE
Conversation show/hide delegate methods

### PR DESCRIPTION
**Pull request by dmkharlamov**
Hello,

this pull request adds new optional methods for `SwrveMessageDelegate` protocol:
- conversationWillBeShown:
- conversationWillBeHidden:

They provide means to react to Conversation appearing/disappearing on screen, e.g. to be able to hide keyboard when Conversation will be be shown.

Some properties and methods of SwrveConversationItemViewController are no longer public, as this class is exposed in new delegate methods now.

### CODE REVIEW

**Comment by dmkharlamov** [comment]
Hello,

are you interested in this change?

**Comment by Sergio-Mira** [comment]
Thanks @dmkharlamov, it looks great! We'll look into adding it to an upcoming release.

**Comment by dmkharlamov** [comment]
Great! 👍

**Comment by KevBrodigan** [comment]
Closing due to lack of customer requests for this feature. can re examine in future if required

**Pull request closed without merging**
