### PR TITLE
9873 Conversation callbacks

### PR DESCRIPTION
**Pull request by Sergio-Mira**
https://swrvedev.jira.com/browse/SWRVE-9873
(Also sync userInfo with QA user methods using the dic as a lock)

### CODE REVIEW

**Comment by Sergio-Mira** [comment]
@dominicmarmionswrve Could you have a look? Will write tests soon

**Comment by Sergio-Mira** [comment]
Waiting response from product, this can (and should) be achieved by the lifecycle callbacks on view controllers.

**Comment by dominicmarmionswrve** [comment]
LGTM

**Comment by Sergio-Mira** [comment]
They can do the same thing detecting that their viewController is being paused. Will write some docs and we can put them in docs.swrve.com

**Pull request closed without merging**
