### PR TITLE
<b> and <i> CSS fixes for conversations

### PR DESCRIPTION
**Pull request by shanethmoore**
Fixed issue where b and i tag styles were not being respected by the phones css which was overwriting styles

### CODE REVIEW

**Comment by shanethmoore** [comment]
@Sergio-Mira @dominicmarmionswrve

**Comment by shanethmoore** [comment]
@dominicmarmionswrve

**Comment by shanethmoore** [comment]
@davemswrve

**Comment by davemswrve** [comment]
CSS changes look a-ok :+1:

**Pull request merged**
