### PR TITLE
Xcode8 updates merge

### PR DESCRIPTION
**Pull request by adam-govan**
@seaders / @dominicmarmionswrve / @Sergio-Mira 

updates for Xcode 8 merged back into the 4.6.1 branch. 

Also, I left in the Short Device ID fix because why not? it's great

### CODE REVIEW

**Comment by Sergio-Mira** [comment]
4.6.1?

**Comment by adam-govan** [comment]
part of the hotfix that I'm doing. it needs to be able to build on Xcode 8

**Comment by Sergio-Mira** [comment]
It is targeted against 4.6, not 4.6.1

**Comment by adam-govan** [comment]
so it is :/

**Pull request closed without merging**
