### PR TITLE
9794 Use a new UIWindow when displaying conversations

### PR DESCRIPTION
**Pull request by Sergio-Mira**
https://swrvedev.jira.com/browse/SWRVE-9794

### CODE REVIEW

**Comment by Sergio-Mira** [comment]
@dominicmarmionswrve @oisin Could you have a quick look?

**Comment by oisin** [comment]
The UIWindow is set to the bounds of the screen, will this cause it to be fullscreen on a tablet, or is the window resized elsewhere?

**Comment by Sergio-Mira** [comment]
The window will be full screen, but the controller won't be. It still displays as a modal when on an iPad and works fine with iOS9 split screen and resizing.

**Comment by oisin** [comment]
:+1:

**Comment by dominicmarmionswrve** [comment]
:rocket:

**Pull request merged**
